kind: pipeline
type: docker
name: Validate

steps:
- name: Test
  image: golang:1.20
  commands:
  - make test
- name: Build
  image: golang:1.20
  commands:
  - make build VERSION="test"
---
kind: pipeline
type: docker
name: Publish

steps:
  - name: Test
    image: golang:1.20
    commands:
    - make test
  - name: Build
    image: golang:1.20
    commands:
    - make build $VERSION
  - name: Example
    image: golang:1.20
    environment:
      USERNAME:
        from_secret: docker_username
    commands:
      - echo "Username is '$USERNAME'"
  - name: Docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: yeslayla/birdbot
      tags:
      - latest
      - $VERSION
---
kind: secret
name: docker_username
get:
  path: secret/cloud/docker
  name: username
---
kind: secret
name: docker_password
get:
  path: secret/cloud/docker
  name: password